FROM node:10-alpine

ENV NODE_ENV production
EXPOSE 3000

WORKDIR /app

RUN mkdir /app/bin /app/src && \
  chown -R guest /app && \
  apk add dumb-init

COPY --chown=guest:root bin /app/bin/

COPY --chown=guest:root package*.json ./
RUN npm ci --only=production

COPY --chown=guest:root src /app/src/

USER guest

CMD ["node", "src/000.js"]
