name: Lint Terraform Templates

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - 'releases/*'

jobs:
  terraform-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.27.0

      - name: Show version
        run: tflint --version

      - name: Run TFLint
        run: tflint -f compact

  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
